/* Main.c file generated by New Project wizard
 *
 * Created:   Sat Nov 14 2015
 * Processor: PIC16F716
 * Compiler:  MPLAB XC8
 */

#include <xc.h>

void main(void)
 {
   // Write your code here
   while (1)
      ;
 }