/* Main.c file generated by New Project wizard
 *
 * Created:   Wed Jul 23 2014
 * Processor: PIC16F887
 * Compiler:  HI-TECH C for PIC10/12/16
 */

#include <htc.h>

void main(void)
 {
   // Write your code here
   while (1)
      ;
 }